In [12]:
import numpy as np

# 1. Create a 1D NumPy array of 10 elements and find its mean, median, and standard deviation.
arr1 = np.array([10, 20, 30, 40, 50, 60, 70, 80,90, 100])
print("1D Array:", arr1)
print("Mean:", np.mean(arr1))
print("Median:", np.median(arr1))
print("Standard Deviation:", np.std(arr1))

1D Array: [ 10  20  30  40  50  60  70  80  90 100]
Mean: 55.0
Median: 55.0
Standard Deviation: 28.722813232690143


In [13]:
# 2. Generate a 3x3 identity matrix and multiply it with another 3x3 random integer matrix.
identity_matrix = np.eye(3)
random_matrix = np.random.randint(1, 10, (3, 3))

result = np.dot(identity_matrix, random_matrix)

print("\nIdentity Matrix:\n", identity_matrix)
print("Random Matrix:\n", random_matrix)
print("Multiplication Result:\n", result)


Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random Matrix:
 [[3 4 1]
 [6 7 4]
 [3 2 6]]
Multiplication Result:
 [[3. 4. 1.]
 [6. 7. 4.]
 [3. 2. 6.]]


In [29]:
# 3. Create a 2D array of shape (4,4) with values from 1 to 16 and extract the 2nd and 3rd columns.
arr2 = np.arange(1, 17).reshape(4, 4)

columns = arr2[:, 1:3]

print("\n4x4 Array:\n", arr2)
print("2nd and 3rd Columns:\n", columns)


4x4 Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2nd and 3rd Columns:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [15]:
# 4. Create two arrays and perform element-wise addition, subtraction, and multiplication.
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)


Addition: [11 22 33]
Subtraction: [ 9 18 27]
Multiplication: [10 40 90]


In [16]:
# 5. Generate a 1D array from 0 to 50 with a step of 5, then reshape it into a 2x5 matrix.
arr3 = np.arange(0, 50, 5).reshape(2, 5)

print("\nReshaped 2x5 Matrix:\n", arr3)



Reshaped 2x5 Matrix:
 [[ 0  5 10 15 20]
 [25 30 35 40 45]]


In [18]:
# 6. Create a random 3x3 matrix, find its transpose, determinant, and inverse.
matrix = np.random.randint(1, 10, (3, 3))

transpose_matrix = matrix.T
determinant = np.linalg.det(matrix)
inverse = np.linalg.inv(matrix)
print("\nRandom 3x3 Matrix:\n", matrix)
print("Transpose:\n", transpose_matrix)
print("Determinant:", determinant)
print("Inverse of Matrix 1:\n", inverse)


Random 3x3 Matrix:
 [[6 2 8]
 [8 2 5]
 [5 7 7]]
Transpose:
 [[6 8 5]
 [2 2 7]
 [8 5 7]]
Determinant: 180.0
Inverse of Matrix 1:
 [[-0.11666667  0.23333333 -0.03333333]
 [-0.17222222  0.01111111  0.18888889]
 [ 0.25555556 -0.17777778 -0.02222222]]


In [19]:
# 7. Generate a 5x5 array of random integers between 10 and 100, and filter out values greater than 50.
arr4 = np.random.randint(10, 101, (5, 5))

filtered = arr4[arr4 > 50]

print("\n5x5 Random Array:\n", arr4)
print("Values greater than 50:\n", filtered)



5x5 Random Array:
 [[ 70  82  96  83  57]
 [ 20  14  38  40  21]
 [ 47  68 100  21  49]
 [ 74  13  21  44  70]
 [ 48  70  35  36  86]]
Values greater than 50:
 [ 70  82  96  83  57  68 100  74  70  70  86]


In [22]:
# 8. Create two 1D arrays and horizontally and vertically stack them using NumPy functions.
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print("\nHorizontal Stack:",  np.hstack((x, y)))
print("Vertical Stack:\n", np.vstack((x, y)))



Horizontal Stack: [1 2 3 4 5 6]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]


In [11]:
# 9. Create an array of 10 random numbers and replace all values greater than the mean with the mean value.
arr5 = np.random.randint(1, 100, 10)

mean_val = np.mean(arr5)
arr5[arr5 > mean_val] = mean_val

print("\nUpdated Array:", arr5)
print("Mean Value:", mean_val)


Updated Array: [41 41  1 18 10 10 41 41 31 31]
Mean Value: 41.5


In [27]:
# 10. Create an array of 20 consecutive numbers and split it equally into 4 sub-arrays
arr6 = np.arange(1, 21)

split_arrays = np.split(arr6, 4)

print("\nOriginal Array:", arr6)
print("\nSplit into 4 sub-arrays:\n", split_arrays)



Original Array: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]

Split into 4 sub-arrays:
 [array([1, 2, 3, 4, 5]), array([ 6,  7,  8,  9, 10]), array([11, 12, 13, 14, 15]), array([16, 17, 18, 19, 20])]
