In [1]:
!pip install numpy

In [24]:
import numpy as np
print("numpy version:", np.__version__)

numpy version: 2.3.5


In [25]:
# Create a 1D array
arr1 = np.array([10, 20, 30, 40, 50])
print("1D Array:\n", arr1)

1D Array:
 [10 20 30 40 50]


In [26]:
# Create a 2D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("2D Array:\n", arr2)
print("\nDimensions of arr2:", arr2.ndim)


2D Array:
 [[1 2 3]
 [4 5 6]]

Dimensions of arr2: 2


In [27]:
# Create a 3D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Array:\n", arr3)

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [28]:
# Check array dimensions
print("\nDimensions of arr3:", arr3.ndim)


Dimensions of arr3: 3


In [29]:
# Array Properties

print("\nArray Shape (rows, columns):", arr2.shape)
print("Array Size (total elements):", arr2.size)
print("Array Data Type:", arr2.dtype)


Array Shape (rows, columns): (2, 3)
Array Size (total elements): 6
Array Data Type: int64


In [30]:
zeros = np.zeros((2, 3))  # 2x3 matrix filled with zeros
print("Zeros Array:\n", zeros)

Zeros Array:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [31]:
ones = np.ones((3, 2))    # 3x2 matrix filled with ones
print("Ones Array:\n", ones)

Ones Array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [32]:
eye = np.eye(3)           # 3x3 identity matrix
print("Identity Matrix:\n", eye)

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
rand = np.random.rand(2, 3)  # Random values between 0 and 1
print("Random Array:\n", rand)

Random Array:
 [[0.07441712 0.7997166  0.72762747]
 [0.35374019 0.73787272 0.19522948]]


In [34]:
arange_arr = np.arange(0, 10, 2)  # Even numbers from 0 to 8
print("Arange Array:\n", arange_arr)

Arange Array:
 [0 2 4 6 8]


In [35]:
linspace_arr = np.linspace(0, 1, 5)  # 5 equally spaced values between 0 and 1
print("Linspace Array:\n", linspace_arr)

Linspace Array:
 [0.   0.25 0.5  0.75 1.  ]


In [36]:
# Array Indexing and Slicing

arr = np.array([10, 20, 30, 40, 50, 60])
print("\nOriginal Array:\n", arr)
print("\nFirst Element:\n", arr[0])
print("\nLast Element:\n", arr[-1])
print("\nSlice [1:4]:\n", arr[1:4])
print("\nEvery 2nd Element:\n", arr[::2])
print("\nEvery 2nd Element:\n", arr[1::2])


Original Array:
 [10 20 30 40 50 60]

First Element:
 10

Last Element:
 60

Slice [1:4]:
 [20 30 40]

Every 2nd Element:
 [10 30 50]

Every 2nd Element:
 [20 40 60]


In [38]:
# 2D Array slicing
arr2d = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("\n2D Array:\n", arr2d)
print("\nElement at [1,2]:\n", arr2d[1, 2])
print("\nFirst two rows and first two columns:\n", arr2d[:2, :2])


2D Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Element at [1,2]:
 60

First two rows and first two columns:
 [[10 20]
 [40 50]]


In [39]:
# Array Operations (Element-wise)

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("\nAddition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Power:", a ** 2)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Power: [1 4 9]


In [40]:
# Statistical and Mathematical Functions

arr = np.array([10, 20, 30, 40, 50, 100])

print("\nSum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Minimum:", np.min(arr))
print("Maximum:", np.max(arr))


Sum: 250
Mean: 41.666666666666664
Median: 35.0
Standard Deviation: 29.1070819942883
Minimum: 10
Maximum: 100


In [3]:
# Reshaping and Flattening Arrays

arr = np.arange(1, 13)
print("\nOriginal 1D Array:", arr)

reshaped = arr.reshape(3, 4)
print("Reshaped to 3x4 Matrix:\n", reshaped)

# reshaped1 = arr.reshape(5, 5)
# print("Reshaped to 3x4 Matrix:\n", reshaped1)

flattened = reshaped.flatten()
print("Flattened Back to 1D:", flattened)


Original 1D Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped to 3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened Back to 1D: [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
# Concatenation and Stacking

x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

print("\nHorizontal Stack:\n", np.hstack((x, y)))
print("Vertical Stack:\n", np.vstack((x, y)))


Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]
Vertical Stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [6]:

# Boolean Indexing and Filtering

arr = np.array([5, 10, 15, 20, 25, 30])
filter_arr = arr > 15
print("\nFilter Boolean Array:", filter_arr)
print("Filtered Values (arr > 15):", arr[filter_arr])


Filter Boolean Array: [False False False  True  True  True]
Filtered Values (arr > 15): [20 25 30]


In [8]:
# Random Numbers in NumPy

print("\nRandom Integer between 1-100:", np.random.randint(1, 100))
print("Random Float:", np.random.random())
print("Random 3x3 Matrix:\n", np.random.randint(10, 50, size=(3, 3)))



Random Integer between 1-100: 75
Random Float: 0.8498280070044771
Random 3x3 Matrix:
 [[18 12 27]
 [24 39 20]
 [26 15 23]]


In [9]:
# Print random 5 x 6 Float matrix
print("Random 5x6 Float Matrix:\n", np.random.random((5, 6)))

Random 5x6 Float Matrix:
 [[0.45818948 0.27945584 0.31699222 0.58209351 0.06360365 0.88316771]
 [0.54219622 0.85900345 0.29807479 0.0832241  0.28682346 0.42833874]
 [0.47650229 0.93823591 0.27250197 0.54765239 0.61431531 0.22212706]
 [0.40395376 0.61859153 0.76748296 0.735276   0.3402491  0.81803945]
 [0.35176416 0.32971076 0.66195336 0.99099458 0.94294614 0.91732002]]


In [5]:
import numpy as np

# Linear Algebra Operations

mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

print("\nMatrix 1:\n", mat1)
print("Matrix 2:\n", mat2)
print("\nMatrix Multiplication:\n", np.dot(mat1, mat2))
print("Transpose of Matrix 1:\n", mat1.T)
print("Determinant of Matrix 1:", np.linalg.det(mat1))
print("Inverse of Matrix 1:\n", np.linalg.inv(mat1))


Matrix 1:
 [[1 2]
 [3 4]]
Matrix 2:
 [[5 6]
 [7 8]]

Matrix Multiplication:
 [[19 22]
 [43 50]]
Transpose of Matrix 1:
 [[1 3]
 [2 4]]
Determinant of Matrix 1: -2.0000000000000004
Inverse of Matrix 1:
 [[-2.   1. ]
 [ 1.5 -0.5]]


In [2]:
# Copy vs View (memory concept)

original = np.array([1, 2, 3, 4])
view_arr = original.view() # Creates a view: shares the same data buffer
copy_arr = original.copy() # Creates a copy: independent data buffer

original[0] = 99 # Modify the original array

print("\nOriginal Array:", original)
print("View Array (Changes reflected):", view_arr)
print("Copy Array (Independent):", copy_arr)


#view(): Creates a new array object that looks at the same data as original. No data is copied.
   # So when original[0] changes to 99, view_arr also shows 99 because both point to the same memory.
        
#copy(): Creates a completely new array with its own data. 
        #Changes to original do not affect copy_arr, which is why it still shows [1 2 3 4].


Original Array: [99  2  3  4]
View Array (Changes reflected): [99  2  3  4]
Copy Array (Independent): [1 2 3 4]
