In [5]:
# Basic installation command:
!pip install tensorflow

In [1]:
# Verify installation:
import tensorflow as tf
print(f"TensorFlow version: {tf.__version__}")
print(f"GPU available: {tf.config.list_physical_devices('GPU')}")

TensorFlow version: 2.21.0
GPU available: []


In [2]:
matrix = tf.constant([[1, 2], [3, 4]])  # 2-D tensor (matrix)
print(matrix)


tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [3]:
scalar = tf.constant(42)  # 0-D tensor (scalar)
vector = tf.constant([1, 2, 3, 4])  # 1-D tensor (vector)
matrix = tf.constant([[1, 2], [3, 4]])  # 2-D tensor (matrix)
tensor_3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # 3-D tensor

print("\nTensor Examples:")
print(f"Scalar shape: {scalar.shape}, value: {scalar.numpy()}")
print(f"Vector shape: {vector.shape}, values: {vector.numpy()}")
print(f"Matrix shape: {matrix.shape}")
print(f"3D Tensor shape: {tensor_3d.shape}")


Tensor Examples:
Scalar shape: (), value: 42
Vector shape: (4,), values: [1 2 3 4]
Matrix shape: (2, 2)
3D Tensor shape: (2, 2, 2)


In [4]:
# Tensor properties

print(f"\nTensor dtype: {matrix.dtype}")
print(f"Tensor rank: {tf.rank(matrix).numpy()}")   # Number of dimensions
print(f"Tensor size: {tf.size(matrix).numpy()}")   # Total elements


Tensor dtype: <dtype: 'int32'>
Tensor rank: 2
Tensor size: 4


In [5]:
# Basic operations
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])

addition = tf.add(a, b)  # or a + b
multiplication = tf.multiply(a, b)  # Element-wise
matmul = tf.matmul(a, b)  # Matrix multiplication

print("\nTensor Operations:")
print(f"Addition:\n{addition.numpy()}")
print(f"Element-wise multiplication:\n{multiplication.numpy()}")
print(f"Matrix multiplication:\n{matmul.numpy()}")


Tensor Operations:
Addition:
[[ 6  8]
 [10 12]]
Element-wise multiplication:
[[ 5 12]
 [21 32]]
Matrix multiplication:
[[19 22]
 [43 50]]


In [6]:
# Common mathematical functions
x = tf.constant([1.0, 2.0, 3.0])
print(f"\nSquare: {tf.square(x).numpy()}")
print(f"Square root: {tf.sqrt(x).numpy()}")
print(f"Exponential: {tf.exp(x).numpy()}")


Square: [1. 4. 9.]
Square root: [1.        1.4142135 1.7320508]
Exponential: [ 2.7182817  7.389056  20.085537 ]


In [7]:
# creating variable

am= tf.constant(10)
a.assign(20)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
a = tf.Variable(10)
a.assign(20)  # Updates value from 10 to 20


In [ ]:
weights = tf.Variable([[1.0, 2.0], [3.0, 4.0]], name="weights")
bias = tf.Variable([0.5, 0.5], name="bias")

print("\nVariable Example:")
print(f"Initial weights:\n{weights.numpy()}")

In [ ]:
weights.assign([[2.0, 3.0], [4.0, 5.0]])
print(f"Updated weights:\n{weights.numpy()}")


In [ ]:
# In-place operations
weights.assign_add([[1.0, 1.0], [1.0, 1.0]])  # Add to existing values

In [ ]:
# 1. Create a scalar tensor with value 10 using tf.constant and print its value and data type.
scalar = tf.constant(10)
print(f"Scalar Value: {scalar.numpy()}")
print(f"Scalar Dtype: {scalar.dtype}")

In [ ]:
# 2. Create a 1-D tensor (vector) [2, 4, 6, 8] using tf.constant and print its shape and numpy value.
vector = tf.constant([2, 4, 6, 8])
print(f"\nVector Shape: {vector.shape}")
print(f"Vector Values: {vector.numpy()}")

In [ ]:
# 3. Create a 2-D tensor (matrix) [[1, 2], [3, 4]] using tf.constant and print its shape and dtype.
matrix = tf.constant([[1, 2], [3, 4]])
print(f"\nMatrix Shape: {matrix.shape}")
print(f"Matrix Dtype: {matrix.dtype}")

In [ ]:
# 4. Create a tf.Variable with initial value 5.0 and print its current value.
a = tf.Variable(5.0)
print(f"\nInitial Variable Value: {a.numpy()}")


In [ ]:
# 5. Update the above variable by assigning it a new value 10.0 using assign() and print the updated value.
a.assign(10.0)
print(f"Updated Variable Value: {a.numpy()}")


In [ ]:
# 6. Use assign_add() on a variable initialized with [[1.0, 2.0], [3.0, 4.0]] to add 1.0 to every element and print the result.
matrix = tf.Variable([[1.0, 2.0], [3.0, 4.0]])
matrix.assign_add([[1.0, 1.0], [1.0, 1.0]])
print(f"\nAfter assign_add():\n{matrix.numpy()}")


In [ ]:
# 7. Create a variable x = 3.0 and inside a tf.GradientTape() block compute y = x**2 + 2*x + 1, then print both x and y.


In [ ]:
# 8. Compute the gradient dy/dx for y = x**2 + 2*x + 1 using tf.GradientTape() and print the gradient value.


In [8]:
# 9. Create two constant tensors a = [[1, 2], [3, 4]] and b = [[5, 6], [7, 8]] and perform matrix multiplication using tf.matmul().
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 6], [7, 8]])
result = tf.matmul(a, b)
print(f"\nMatrix Multiplication Result:\n{result.numpy()}")



Matrix Multiplication Result:
[[19 22]
 [43 50]]


In [37]:
# 10. Create a random tensor of shape (3, 3) using tf.random.uniform() and print its shape, dtype, and values.
random_tensor = tf.random.uniform((3, 3))
print(f"\nRandom Tensor Shape: {random_tensor.shape}")
print(f"Random Tensor Dtype: {random_tensor.dtype}")
print(f"Random Tensor Values:\n{random_tensor.numpy()}")


Random Tensor Shape: (3, 3)
Random Tensor Dtype: <dtype: 'float32'>
Random Tensor Values:
[[0.01198125 0.15286887 0.9999075 ]
 [0.46857226 0.6109365  0.4359038 ]
 [0.35625827 0.2546016  0.10136735]]
